name: Run Tests

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7, 3.8 ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Stop MySQL
      run: sudo /etc/init.d/mysql stop
    - name: Upgrade Pip
      run: sudo python -m pip install --upgrade pip
    - name: Upgrade Pip
      run: sudo python -m pip install -U pip setuptools
    - name: Test Requirements
      run: pip install --user -r requirements/tests.txt
    - name: Install App
      run: sudo pip install --user .
    - name: Run Tests
      run: sudo python -m pytest --headless --cov=reflect